"""Multi-object tracker built on ByteTrack.

Ultralytics ships ByteTrack; we drive it through ``model.track(persist=True)``
so each object keeps a stable ``track_id`` across frames. The tracker reuses
the ``Detector``'s already-loaded model to avoid double memory cost, and
returns rich ``TrackedObject`` instances (with centroid history) that the rule
engine consumes.

Track history is capped so memory stays bounded on long-running streams.
"""

from __future__ import annotations

import os
import tempfile
from collections import defaultdict, deque
from typing import Deque, Dict, List, Tuple

import numpy as np

from detector.detector import Detector
from detector.types import ObjectClass, TrackedObject
from logging_utils import get_logger

logger = get_logger(__name__)

# Stock ByteTrack (ultralytics' bytetrack.yaml) hardcodes track_high_thresh
# and new_track_thresh at 0.25, regardless of our own conf_threshold. A
# small/held trash object is often detected below 0.25 -- our Detector still
# passes it through (conf_threshold defaults to 0.15), but ByteTrack then
# silently refuses to ever assign it a track id, so it never reaches the
# rule engine. Only "person" (usually >0.5 confidence) reliably clears
# ByteTrack's own bar. We generate a tracker config whose thresholds track
# our own conf_threshold instead, once per distinct value.
#
# fuse_score is also forced off: a brand-new track only survives to a 2nd
# frame (and thus ever gets a track id) if it clears a threshold of 0.7 in
# ultralytics' unconfirmed-track association step -- a constant hardcoded
# in ultralytics itself, not exposed by this yaml. With fuse_score on, that
# match cost is (IoU * detection score), so anything detected below
# roughly ~0.5-0.6 confidence can *never* clear 0.7 no matter how stable
# its box is -- silently starving every low-confidence trash detection of
# a track id. Pure-IoU matching (fuse_score off) lets a stationary/slow
# object confirm on geometry alone, which is what we need at conf~0.15-0.35.
_TRACKER_CONFIG_CACHE: Dict[float, str] = {}


def _bytetrack_config_path(min_conf: float) -> str:
    """Return a ByteTrack config path whose thresholds match ``min_conf``."""
    cached = _TRACKER_CONFIG_CACHE.get(min_conf)
    if cached is not None:
        return cached
    content = (
        "tracker_type: bytetrack\n"
        f"track_high_thresh: {min_conf}\n"
        f"track_low_thresh: {max(0.05, min_conf / 2):.3f}\n"
        f"new_track_thresh: {min_conf}\n"
        "track_buffer: 60\n"
        "match_thresh: 0.8\n"
        "fuse_score: false\n"
    )
    fd, path = tempfile.mkstemp(prefix="smart_litter_bytetrack_", suffix=".yaml")
    with os.fdopen(fd, "w") as f:
        f.write(content)
    _TRACKER_CONFIG_CACHE[min_conf] = path
    logger.info("Generated ByteTrack config (thresh=%.2f) at %s", min_conf, path)
    return path


# How many past centroids to keep per track (enough for motion analysis).
_MAX_HISTORY = 150

# Drop a track's history once it has gone unseen for this many consecutive
# frames -- otherwise ``_history`` grows without bound as ByteTrack hands out
# new ids over a long-running / RTSP stream.
_MAX_MISSING_FRAMES = 150


class Tracker:
    """Wraps ByteTrack, yielding tracked objects per frame."""

    def __init__(self, detector: Detector) -> None:
        self._detector = detector
        # Persistent per-track centroid history keyed by track id.
        self._history: Dict[int, Deque[Tuple[float, float]]] = defaultdict(
            lambda: deque(maxlen=_MAX_HISTORY)
        )
        # Consecutive frames each known track has gone unseen.
        self._missing: Dict[int, int] = defaultdict(int)

    def update(self, image: np.ndarray) -> List[TrackedObject]:
        """Detect + track objects in one frame.

        Args:
            image: BGR frame.

        Returns:
            Tracked objects (MVP classes only) present in this frame, each
            carrying its centroid history.
        """
        results = self._detector.model.track(
            image,
            persist=True,          # keep tracker state between calls
            tracker=_bytetrack_config_path(self._detector.conf_threshold),
            conf=self._detector.conf_threshold,
            device=self._detector.device,
            imgsz=self._detector.imgsz,
            verbose=False,
        )

        tracked: List[TrackedObject] = []
        seen_ids: set[int] = set()

        for result in results:
            if result.boxes is None or result.boxes.id is None:
                continue  # no tracks this frame
            names = result.names
            for box in result.boxes:
                if box.id is None:
                    continue
                coco_name = names.get(int(box.cls.item()), "")
                mapped: ObjectClass | None = Detector.map_class(coco_name)
                if mapped is None:
                    continue

                track_id = int(box.id.item())
                seen_ids.add(track_id)
                x1, y1, x2, y2 = box.xyxy[0].tolist()
                cx, cy = (x1 + x2) / 2.0, (y1 + y2) / 2.0
                self._history[track_id].append((cx, cy))

                tracked.append(
                    TrackedObject(
                        track_id=track_id,
                        cls=mapped,
                        confidence=float(box.conf.item()),
                        bbox=(x1, y1, x2, y2),
                        history=list(self._history[track_id]),
                    )
                )

        self._prune_missing(seen_ids)
        return tracked

    def _prune_missing(self, seen_ids: set[int]) -> None:
        """Drop history for tracks unseen too long; reset the counter for the rest."""
        for track_id in list(self._history.keys()):
            if track_id in seen_ids:
                self._missing[track_id] = 0
                continue
            self._missing[track_id] += 1
            if self._missing[track_id] > _MAX_MISSING_FRAMES:
                del self._history[track_id]
                del self._missing[track_id]
